kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    app: fuse-buckets
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: http
  type: NodePort
---  
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fuse-buckets
    spec:
      volumes:
        - name: nginx-content
          emptyDir: {}
      containers:
      - name: "nginx"
        image: "ageapps/k8s-storage-buckets:nginx"
        ports:
          - name: http
            containerPort: 8080
        volumeMounts:
          - name: nginx-content
            mountPath: /content
        lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
      - name: gcsfuse-mounter
        image: "ageapps/k8s-storage-buckets:gcsfuse-sync"
        command: ['sh', '-c', 'bash /gcsfuse/setUp.sh']
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        env:
          - name: FUSE_MOUNT_DIR
            value: "/gcsfuse/buckets/fuse-test-bucket"
          - name: FUSE_BUCKET_NAME
            value: "fuse-test-bucket"
        volumeMounts:
          - name: nginx-content
            mountPath: /gcsfuse/buckets/fuse-test-bucket
     